export { default as useAuth } from './useAuth'
export { default as useCourses } from './useCourses'
export { default as useLessons } from './useLessons'
export { default as useProgress } from './useProgress'
export { default as useNotifications } from './useNotifications'
export { default as useMediaQuery, useIsMobile, useIsTablet, useIsDesktop, useIsDarkMode } from './useMediaQuery'
export { default as useLocalStorage, useThemePreference, useUserPreferences, useRecentCourses, useViewMode } from './useLocalStorage'